version: '3.1'


services:

  redis-sentinel:
    image: khrost1905/redis-sentinel:${TAG:-latest}
    environment:
      - REDIS_IP=redis-zero
      - REDIS_MASTER_NAME=redismaster
    deploy:
      replicas: 4
    networks:
      - redis

  redis:
    image: khrost1905/redis-look:1
    environment:
      - REDIS_SENTINEL_IP=redis-sentinel
      - REDIS_MASTER_NAME=redismaster
      - REDIS_SENTINEL_PORT=26379
    deploy:
      replicas: 4
    networks:
      - redis

networks:
  redis:
    external: true

